[package]
name = "repeat_image_bot"
version = "0.1.0"
authors = ["my name <my@email.address>"]
edition = "2021"

[dependencies]
telexide = { path = "../../" }
tokio = { version = "1", features = ["full"] }
env_logger = "0.9"
log = "0.4"
